version: "3.9"
services:
  backend:
    build: ./rz_api/
    volumes:
      - ./rz_api/rz.sqlite:/opt/app/rz.sqlite
    restart: always

  front:
    build: ./slavasql/
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    restart: always
